### ISSUE TITLE
JITSupport use breaks tests under non-CRuby

### ISSUE THREAD

**Issue by headius** [ruby/open3#2]
In 590e09bf5999d3b843bdcfcf83750e613568726d @k0kubun added logic to clear JIT logs during the popen2 test using JITSupport.

This breaks the test on implementations that do not have the same JIT flags and RubyVM support as CRuby.

If this logic is still necessary for the test to run on CRuby with JIT enabled, it should be masked to only run on CRuby. If it is no longer needed it should be reverted.

The rest of the `jit_support.rb` file does not seem to be used and was only ported over because it's used by the full test suite in CRuby (ac2e7bdfd46401c4ea2d49dd3b56ef5f30fd4f98 by @hsbt).

I have some changes coming to let the open3 tests run on JRuby and include our Windows support files (JRuby only launches subprocesses through Java APIs on Windows, so different logic is required) and can also include this fix.

**Comment by headius** [comment]
@k0kubun Will that get wiped out if someone updates `jit_support.rb` from CRuby again? I do not know the CRuby stdlib maintenance workflow, but such things have happened in the past.

**Comment by k0kubun** [comment]
I have never sync-ed `test/lib` from ruby/ruby to other repositories. So it's up to hsbt. But I suppose you can also just update the same file in ruby/ruby if you have the concern.

**Comment by headius** [comment]
I will wait to hear from @hsbt before changing the logic in #3. Thanks!
